### ISSUE TITLE
Animations running really slow on some devices?

### ISSUE THREAD

**Issue by shaheenzahedi** [amirh/indux#2]
I have tested this app on about ten android devices, and I don't know why on some devices it executes animation really slow, and on some devices it executes just fine, it's not about the API level it's not about the GPU, but the overall result in some devices is majorly different.

and as I told ya I optimized the algorithm, but it still runs the animations slowly, here is the list of devices I have tested.

Galaxy j7 2016 (smooth)
Xperia Z3 (slow)
Huawei Hol-u19 (fine)
Galaxy Tab S2 (terrible)
Techno W1 dual sim (good)

I have video from some devices I will upload it if you want to

**Comment by shaheenzahedi** [comment]
Here is the video on Galaxy Tab S2
[https://youtu.be/YoLSupCjMIc](url)

**Comment by amirh** [comment]
Hi, it's hard to tell from your video what exactly is going on in your code.
One guess would be that you're hitting the same issue as flutter/flutter/issues/13736, you can try to remove the fade animation to verify.

If you're hitting a flutter performance issue, please try to narrow it down to the smallest code example that reproduces the problem and file it as a Flutter issue.

Note that this repository is just an example for the redux/animations concept I was playing with, and it is not maintained nor is the 2048 example.
